export const ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN',
);
export const BALANCE_REPOSITORY_TOKEN = Symbol('BALANCE_REPOSITORY_TOKEN');
export const MBTI_REPOSITORY_TOKEN = Symbol('MBTI_REPOSITORY_TOKEN');
export const ADJECTIVE_EXPRESSION_SERVICE_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_SERVICE_TOKEN',
);
export const BALANCE_SERVICE_TOKEN = Symbol('BALANCE_SERVICE_TOKEN');
export const MBTI_SERVICE_TOKEN = Symbol('MBTI_SERVICE_TOKEN');
export const ADJECTIVE_EXPRESSION_REPOSITORY_READ_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_REPOSITORY_READ_TOKEN',
);
export const BALANCE_READ_REPOSITORY_TOKEN = Symbol(
  'BALANCE_READ_REPOSITORY_TOKEN',
);
export const MBTI_REPOSITORY_READ_TOKEN = Symbol('MBTI_REPOSITORY_READ_TOKEN');
