export const ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN',
);
export const BALANCE_REPOSITORY_TOKEN = Symbol('BALANCE_REPOSITORY_TOKEN');
export const USER_MBTI_REPOSITORY_TOKEN = Symbol('USER_MBTI_REPOSITORY_TOKEN');
export const ADJECTIVE_EXPRESSION_SERVICE_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_SERVICE_TOKEN',
);
export const USER_BALANCE_SERVICE_TOKEN = Symbol('USER_BALANCE_SERVICE_TOKEN');
export const USER_MBTI_SERVICE_TOKEN = Symbol('USER_MBTI_SERVICE_TOKEN');
export const ADJECTIVE_EXPRESSION_REPOSITORY_READ_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_REPOSITORY_READ_TOKEN',
);
export const BALANCE_READ_REPOSITORY_TOKEN = Symbol(
  'BALANCE_READ_REPOSITORY_TOKEN',
);
