version: "3.7"

services:
  postgres-container:
    container_name: 308_poten_day_db
    image: postgres:15
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - SERVER_PORT=3000
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - 308_poten_day_network

  read-postgres-container:
    container_name: 308_poten_day_read_db
    image: postgres:15
    ports:
      - ${READ_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${READ_DB_USERNAME}
      - POSTGRES_PASSWORD=${READ_DB_PASSWORD}
      - POSTGRES_DB=${READ_DB_DATABASE}
      - SERVER_PORT=3000
    volumes:
      - ./read-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - 308_poten_day_network

networks:
  308_poten_day_network:
    driver: bridge
