version: '3.7'

services:
  nestjs_server:
    container_name: server
    image: jimin8830/potenday:icegame
    volumes:
      - /usr/src/potenday/app/node_modules
    ports:
      - 3000:3000
    restart: always
    networks:
      - test-networks

networks:
  test-networks:
    driver: bridge
