version: '3.7'

services:
  postgres-container:
    container_name: 308_poten_day_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'wlals12!'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - test-networks

networks:
  test-networks:
    driver: bridge
