export const ERROR_CODES = {
  DELETE_USER: 'DELETE_USER',

  NOT_FOUND_URL: 'NOT_FOUND_URL',
  ALREADY_CLICK_BUTTON_URL: 'ALREADY_CLICK_BUTTON_URL',
  MAXIMUM_URL: 'MAXIMUM_URL',
  STATUS_FALSE_URL: 'URL_STATUS_FALSE',
  UPDATE_URL: 'UPDATE_URL',
  UPDATE_URL_USER_ID_LIST: 'UPDATE_URL_USER_ID_LIST',
  DELETE_URL: 'DELETE_URL',
  DELETE_URL_USER_ID: 'DELETE_URL_USER_ID',

  SUBMIT_ADJECTIVE_EXPRESSION: 'SUBMIT_ADJECTIVE_EXPRESSION',
  UPDATE_ADJECTIVE_EXPRESSION_SUBMIT: 'UPDATE_ADJECTIVE_EXPRESSION_SUBMIT',
  DELETE_ADJECTIVE_EXPRESSION_SUBMIT: 'DELETE_ADJECTIVE_EXPRESSION_SUBMIT',
  DELETE_ADJECTIVE_EXPRESSION_LIST_SUBMIT:
    'DELETE_ADJECTIVE_EXPRESSION_LIST_SUBMIT',

  SUBMIT_USER_BALANCE: 'SUBMIT_USER_BALANCE',
  UPDATE_BALANCE: 'UPDATE_BALANCE',
  NOT_FOUND_BALANCE_LIST: 'NOT_FOUND_BALANCE_LIST',
  DELETE_BALANCE: 'DELETE_BALANCE',
  NOT_FOUND_BALANCE: 'NOT_FOUND_BALANCE',

  SUBMIT_USER_MBTI: 'USER_MBTI_SUBMIT',
  CREATE_MBTI: 'CREATE_MBTI',
  NOT_FOUND_MBTI: 'NOT_FOUND_MBTI',
  DELETE_MBTI: 'DELETE_MBTI',

  TYPEORM_UPDATE: 'TYPEORM_UPDATE',
} as const;
export type ERROR_CODE = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
