export const ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  URL_NOT_FOUND: 'URL_NOT_FOUND',
  URL_ALREADY_CLICK_BUTTON: 'URL_ALREADY_CLICK_BUTTON',
  URL_MAXIMUM_USER: 'URL_MAXIMUM_USER',
  URL_STATUS_FALSE: 'URL_STATUS_FALSE',

  USER_ADJECTIVE_EXPRESSION_SUBMIT: 'USER_ADJECTIVE_EXPRESSION_SUBMIT',

  USER_BALANCE_SUBMIT: 'USER_BALANCE_SUBMIT',

  USER_MBTI_SUBMIT: 'USER_MBTI_SUBMIT',
} as const;
export type ERROR_CODE = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
