export const ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN = Symbol(
  'ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN',
);
export const USER_ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN = Symbol(
  'USER_ADJECTIVE_EXPRESSION_REPOSITORY_TOKEN',
);
export const COMMON_QUESTION_REPOSITORY_TOKEN = Symbol(
  'COMMON_QUESTION_REPOSITORY_TOKEN',
);
export const BALANCE_LIST_REPOSITORY_TOKEN = Symbol(
  'BALANCE_LIST_REPOSITORY_TOKEN',
);
export const USER_BALANCE_REPOSITORY_TOKEN = Symbol(
  'USER_BALANCE_REPOSITORY_TOKEN',
);
export const USER_MBTI_REPOSITORY_TOKEN = Symbol('USER_MBTI_REPOSITORY_TOKEN');
