export const USER_REPOSITORY_TOKEN = Symbol('USER_REPOSITORY_TOKEN');
export const USER_URL_REPOSITORY_TOKEN = Symbol('USER_URL_REPOSITORY_TOKEN');
export const USER_URL_SERVICE_TOKEN = Symbol('USER_URL_SERVICE_TOKEN');
export const USER_URL_EVENT_PUBLISHER = Symbol('USER_URL_EVENT_PUBLISHER');
