export const USER_REPOSITORY_TOKEN = Symbol('USER_REPOSITORY_TOKEN');
export const URL_REPOSITORY_TOKEN = Symbol('URL_REPOSITORY_TOKEN');
export const USER_URL_SERVICE_TOKEN = Symbol('USER_URL_SERVICE_TOKEN');
export const URL_READ_REPOSITORY_TOKEN = Symbol('URL_READ_REPOSITORY_TOKEN');
export const USER_READ_REPOSITORY_TOKEN = Symbol('USER_READ_REPOSITORY_TOKEN');
